[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino

monitor_speed = 115200

lib_deps =
    bodmer/TFT_eSPI
    paulstoffregen/XPT2046_Touchscreen
    madhephaestus/ESP32Servo

; ==== TFT_eSPI serttings ====
build_flags = -DTFT_WIDTH=320 -DTFT_HEIGHT=480 -DLOAD_ILI9486_DRIVER -DSPI_FREQUENCY=27000000 -DTFT_MOSI=23 -DTFT_SCLK=18 -DTFT_BL=14 -DTOUCH_CS=4 -DTOUCH_IRQ=27 -DTFT_CS=5 -DTFT_DC=21 -DTFT_RST=22